version: '3'

services:
  pd-server:
    image: pingcap/pd:latest
    command:
      - --name=pd1
      - --data-dir=/pd
      - --client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://pd-server:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-peer-urls=http://pd-server:2380
      - --initial-cluster=pd1=http://pd-server:2380
    ports:
      - "2379:2379"
      - "2380:2380"

  tikv-server:
    image: tikv/tikv:latest
    command:
      - --pd=pd-server:2379
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv-server:20160
    ports:
      - "20160:20160"
    depends_on:
      - pd-server

  go-app:
    image: tikvapi
    ports:
      - "8080:8080"
    depends_on:
      - tikv-server
